### PR TITLE
DOC: update stable docs with new mailing list info

### PR DESCRIPTION
**Pull request by nelson-liu**
I edited the rst and html files for the 0.17 docs to reflect changes to the mailing list. cc @agramfort

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

@amueller @ogrisel ok for you?

**Comment by GaelVaroquaux** [comment]
Isn't this the wrong repo? Docs are stored in the doc folder of the main
repo.

**Comment by nelson-liu** [comment]
@GaelVaroquaux a patch has been merged in the main repo, but the doc folder there is for the dev documentation, right? It was proposed in https://github.com/scikit-learn/scikit-learn/pull/6812 to update the stable documentation as well.

**Comment by amueller** [comment]
I think this is the right thing to do. This is the rendered website, which we want to change. We don't want to have people subscribe to the wrong mailing list until the next release.

LGTM

**Comment by jnothman** [comment]
The other way of doing it is backporting the changes to the tagged version
and recompiling... but why bother?

**Comment by amueller** [comment]
the recompiling currently still requires a manual upload, right? Or is building the stable docs also automatic now?

**Comment by jnothman** [comment]
Indeed.

**Comment by jnothman** [comment]
I think we should merge here. LGTM.

**Pull request merged**
