### PR TITLE
 fix typo

### PR DESCRIPTION
**Pull request by Gabriel-p**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Thanks for the pull request. However, the documentation is not maintained on this repository, but generated from rst files in the scikit-learn repository. In addition, I think that the fix is not correct. I think that 'provably' was intended, and not 'probably'.

**Comment by Gabriel-p** [comment]
Got it, thanks for the heads up on both counts.

**Comment by ogrisel** [comment]
I disabled the issues feature on this repo but I could not disable the pull requests apparently...

**Comment by ogrisel** [comment]
I added a README.md to the repo.

**Comment by GaelVaroquaux** [comment]
Maybe a 'Contributing'?

**Comment by ogrisel** [comment]
will duplicate the file.

**Pull request closed without merging**
