### PR TITLE
point stable to 0.20

### PR DESCRIPTION
**Pull request by qinhanmin2014**
http://scikit-learn.org/stable/documentation.html still links to 0.19.2, According to git log, I think this is the right solution. ping @jnothman

### CODE REVIEW

**Comment by jnothman** [comment]
Not until we release 0.20 final. At the moment we do not even have the RC
annouced or wheels published

**Comment by amueller** [comment]
Yeah only after final

**Comment by ogrisel** [comment]
Sorry @qinhanmin2014 , I had not seen that PR. BTW how did you make the change for this PR? Using git or using the github UI. When I tried to use the github UI it broken the website. I had to do a depth 1 clone to be able to do a proper commit to update the symlink.

**Comment by qinhanmin2014** [comment]
>  I had not seen that PR. BTW how did you make the change for this PR? Using git or using the github UI. When I tried to use the github UI it broken the website.

Thanks for finishing this. I'm using Github Desktop (under Windows) for these simple PRs and I have no idea why the website was down. Happy to see it working now.

**Pull request closed without merging**
