### PR TITLE
A very critical error on the installation documentation (I think)

### PR DESCRIPTION
**Pull request by alvations**
On the [installation page](http://scikit-learn.org/stable/install.html), it says:

"**We don’t recommend installing scipy or numpy using pip on linux**, as this will involve a lengthy build-process with many dependencies. Without careful configuration, building numpy yourself can lead to an installation that is much slower than it should be. If you are using Linux, consider using your package manager to install scikit-learn. It is usually the easiest way, but might not provide the newest version. If you haven’t already installed numpy and scipy and can’t install them via your operation system, it is recommended to use a third party distribution."

Isn't it suppose to be **We recommend installing scipy or numpy using pip on linux**?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
> Isn't it suppose to be We recommend installing scipy or numpy using pip on
> linux?

No, it's not. We _do not_ recommend it.

**Comment by alvations** [comment]
Okay? So it's you recommend to use `conda` or other package manager?

**Comment by GaelVaroquaux** [comment]
> Okay? So it's you recommend to use conda or other package manager?

Yes. There reason being that scipy and numpy need tricky compiled
libraries that are outside the scope of Python packaging.

The formulation might be unclear. If you feel you can improve it, we'd
love a pull request on the other repo (the main scikit-learn one).

Thanks!

**Comment by alvations** [comment]
What if we change the wording to:

```
If you are using Linux, consider using your package manager, e.g. 
*yum, apt-get, dpkg, zypper, etc.*, to install
scikit-learn. It is usually the easiest way, but might not provide the newest
version.
```

**Pull request closed without merging**
